### ISSUE TITLE
stripe 无法支付

### ISSUE THREAD

**Issue by lufeiit** [BobCoderS9/SSPanel-Metron#9]
填写完整stripe后在商店页面无法支付，提示500错误，

nginx错误信息
2021/09/22 14:36:49 [error] 21820#0: *9556242 FastCGI sent in stderr: "PHP message: Slim Application Error:
Type: Error
Message: Function name must be a string
File: /www/wwwroot/sspanel/src/Services/Gateway/StripePay.php
Line: 30
Trace: #0 /www/wwwroot/sspanel/src/Services/Gateway/MetronPay.php(173): App\Services\Gateway\StripePay->MetronPay()
#1 /www/wwwroot/sspanel/src/Services/Payment.php(76): App\Services\Gateway\MetronPay->purchase()
#2 [internal function]: App\Services\Payment::purchase()
#3 /www/wwwroot/sspanel/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func()
#4 /www/wwwroot/sspanel/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke()
#5 /www/wwwroot/sspanel/src/Middleware/Auth.php(26): Slim\Route->__invoke()
#6 [internal function]: App\Middleware\Auth->__invoke()
#7 /www/wwwroot/sspanel/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()
#8 [internal function]: Slim\DeferredCallable->__invoke()
#9 /www/wwwroot/sspanel/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70)" while reading response header from upstream, client: 172.70.188.48, server: ****, request: "POST /user/payment/purchase HTTP/2.0", upstream: "fastcgi://unix:/tmp/php-cgi-74.sock:", host: "****", referrer: "https://****/user/shop"

**Comment by BobCoderS9** [comment]
这个建议你找其他人修改测试，我这边没有stripe账号，不方便测试
